#!/usr/bin/env bash
# Install a nginx web server
# Return a page that contain the string Hello World!

sudo apt-get -y update
sudo apt-get -y install nginx
echo "Hello World!" | sudo tee /var/www/html/index.html
sudo service nginx restart
