#!/usr/bin/env bash
# Install a nginx web server
# Return a page that contain the string Hello World!
# This is also a redirection page
# This is to diplay an error page

# a replacement string
string_for_replacement="server_name _;\n\trewrite ^\/redirect_me https:\/\/www.youtube.com\/watch?v=QH2-TGUlwu4 permanent;"

# nginx installation
sudo apt-get -y update
sudo apt-get install -y nginx

# This to get an output from the default server output
echo "Hello World!" | sudo tee /var/www/html/index.html

# Performing a redirection
sudo sed -i "s/server_name _;/$string_for_replacement/" /etc/nginx/sites-enabled/default

# Creating a 404 erro page
echo "Ceci n'est pas une page" | sudo tee /var/www/html/404.html
string_for_replace="listen 80 default_server;\n\terror_page 404 \/404.html;\n\tlocation = \/404.html {\n\troot \/var\/www\/html;\n\t\tinternal;\n\t}"
sudo sed -i "s/listen 80 default_server;/$string_for_replace/" /etc/nginx/sites-enabled/default
