#!/usr/bin/env bash
#what type of network a computer in local is connected to
#what type of network could an office in one building to another office in a building free streets way?
#what network do you use when you browse www.google.com from your smartphone(not connected to wifi)?

3
2
1
