#!/usr/bin/bash
#displays numbers from 1 to 20

i=1

while [ "$i" -lt 21 ]; do

    case "$i" in 
        4)
            echo "$i"
            echo "back luck from china"
            ;;
        9)
            echo "$i"
            echo "back luck from japan"
            ;;
        17)
            echo "$i"
            echo "back luck from italy"
            ;;
        *)
            echo "$i"
            ;;
        esac

        ((i++))
    done

